### ISSUE TITLE
RTSP Server RECORD

### ISSUE THREAD

**Issue by ancelotpinto** [revmischa/rtsp-server#1]
The readme describes ffmpeg as a client supporting the "RECORD" request. I can't get the necessary flags to send the "RECORD" request.

ffmpeg -re -i input -f rtsp -muxdelay 0.1 rtsp://server/live.sdp
The above command works just fine for streaming for others to watch. Please help with the flag for recording.

Ancelot Mark Pinto
Mumbai, India

**Comment by revmischa** [comment]
Did you include a sdp path? Something like: `rtsp://localhost:9999/live.sdp` ?
