### ISSUE TITLE
Missing package 

### ISSUE THREAD

**Issue by xandark** [revmischa/rtsp-server#15]
From the README.md, there is a missing package, and if it's not installed then Perl will barf when running "make test".

```
#   Failed test 'use RTSP::Server;'
#   at t/RTSP-Server.t line 9.
#     Tried to use 'RTSP::Server'.
#     Error:  Can't locate URI.pm in @INC (you may need to install the URI module) (@INC contains: ....
```

To solve, please add this line to the INSTALLATION instructions:
     sudo apt-get install liburi-perl

Also, the "sudo apt-get instal libmoose-perl" is misspelling "install".

**Comment by revmischa** [comment]
I really thought URI was in core. What perl are you using exactly?

**Comment by revmischa** [comment]
https://github.com/revmischa/rtsp-server/commit/1ca5900d7f25320574b4894fa824b48928386f4c

**Comment by xandark** [comment]
Hello, I'm using Debian Jessie Perl from the Raspberry Pi distro called Raspbian, fully up to date. Here's the details:

Package: perl
Version: 5.20.2-3+deb8u6
Maintainer: Niko Tyni <ntyni@debian.org>

**Comment by xandark** [comment]
Okay, saw that you added the package, thanks!
