### ISSUE TITLE
Location of log?

### ISSUE THREAD

**Issue by xandark** [revmischa/rtsp-server#17]
Where is the log file for rtsp-server located? I notice that it doesn't output to the console even with --loglevel set to 0. 

I need to see why this server is refusing my requests or even that it's accepting requests.

**Comment by revmischa** [comment]
Try setting it to 5, not 0

**Comment by xandark** [comment]
Yes, thank you for that clarification, that is helping tremendously.

When I invoked rtsp-server with the -h argument, the usage info didn't indicate the range for --loglevel nor the expected results.

If that were changed, I'm sure it would save others the same guessing. It would be great to know that it only logs to stdout too.

**Comment by revmischa** [comment]
Patches welcome, homeslice
