### ISSUE TITLE
Setup error

### ISSUE THREAD

**Issue by lewang0418** [revmischa/rtsp-server#4]
Hi,

rtsp-server works fine with ffmpeg. However, when I tried to connect other rtsp client to the server I get the follow error.

---

./rtsp-server.pl -s 9999 -c 9998 -l 4
Starting RTSP server, log level = 4
Source server started
Client server started
Source connection from 10.0.0.147:53592
Got method OPTIONS
Got method ANNOUNCE
Got source announcement for rtsp://10.0.0.151:9999/live/myStream
Mounted /live/myStream
Got method SETUP
Use of uninitialized value $stream_id in concatenation (.) or string at lib/RTSP/Server/Source/Connection.pm line 162.
Got SETUP request for stream 
Error handling SETUP: Can't call method "get_stream" on an undefined value at lib/RTSP/Server/Source/Connection.pm line 176.
## Got EOF on listener

Would you please look at it?

**Comment by revmischa** [comment]
Can you enable the logging of requests/responses? Is this the same issue as https://github.com/revmischa/rtsp-server/issues/6 ?

**Comment by mvardan** [comment]
I have the same issue. I am using gstreamer's rtspclientsink to connect pipe with your server.

root@mvardan:/home/mvardan/devel/rtsp-server# ./rtsp-server.pl -l4
Starting RTSP server, log level = 4
Source server started
Client server started
Source connection from 192.168.0.101:45628
Got method OPTIONS
Got method ANNOUNCE
Got source announcement for rtsp://192.168.0.101:5545/abc
Mounted /abc
Got method SETUP
Use of uninitialized value $stream_id in concatenation (.) or string at lib/RTSP/Server/Source/Connection.pm line 162.
Got SETUP request for stream 
Error handling SETUP: Can't call method "get_stream" on an undefined value at lib/RTSP/Server/Source/Connection.pm line 176.

Got EOF on listener
Source connection from 192.168.0.101:45632
Got method OPTIONS
Got EOF on listener

Here is my pipe

gst-launch-1.0 v4l2src device=/dev/video0 ! video/x-raw ! queue ! videoconvert ! rtspclientsink location=rtsp://192.168.0.101:5545/abc name=s

and result log of running of that pipe

Setting pipeline to PAUSED ...
Pipeline is live and does not need PREROLL ...
Progress: (open) Opening Stream
Progress: (connect) Connecting to rtsp://192.168.0.101:5545/abc
Progress: (open) Retrieving server options
Progress: (open) Opened Stream
Setting pipeline to PLAYING ...
New clock: GstSystemClock
Progress: (request) Sending RECORD request
Progress: (record) Sending server stream info
Progress: (request) SETUP stream 0
0:00:33.499572350 31508      0x21b1cf0 ERROR         rtspclientsink gstrtspclientsink.c:4170:gst_rtsp_client_sink_record:<s> setup failed
ERROR: from element /GstPipeline:pipeline0/GstRTSPClientSink:s: Could not read from resource.
Additional debug info:
gstrtspclientsink.c(2712): gst_rtsp_client_sink_try_send (): /GstPipeline:pipeline0/GstRTSPClientSink:s:
Could not receive message. (Timeout while waiting for server response)
Execution ended after 0:00:33.458415189
Setting pipeline to PAUSED ...
Setting pipeline to READY ...
Setting pipeline to NULL ...
Freeing pipeline ...

**Comment by revmischa** [comment]
Hey get back in #gstreamer

**Comment by mvardan** [comment]
Sorry I was off line.

**Comment by mvardan** [comment]
I succeed to setup gstreamer pipe which streamed to server from this fork (https://github.com/nosolosoftware/rtsp-server/commits/master). But it was too unstable in comparison with ffmpeg streaming.

**Comment by revmischa** [comment]
Ok my guess is the streamID is not numeric:

```
    my ($stream_id) = $path =~ m!/streamid=(\d+)!sm;
    $path =~ s!/streamid=(\d+)!!sm;
```

It looks like this fork was experimenting with fixing this parsing
https://github.com/nosolosoftware/rtsp-server/commit/ec71072dce6e7f6178844bfb5072021ff4bc467e

I'm not sure what the correct way to parse the streamID is. We could try something more flexible like `\w`
