### ISSUE TITLE
Not working anymore with ffmpeg ?

### ISSUE THREAD

**Issue by sladecraven** [revmischa/rtsp-server#6]
Hi, 

Just tested with RTSP::Server from CPAN and ffmpeg, and if get the following error message on ffmpeg side : 
[rtsp @ 0x2616520] method ANNOUNCE failed: 405 Method Not Allowed

On rtsp_server side : 

Client connection from 127.0.0.1:51991
Client listener: >> OPTIONS rtsp://127.0.0.1:8666/live02 RTSP/1.0
Got method OPTIONS
Client listener: >> CSeq: 1
Client listener: >> User-Agent: Lavf56.40.101
Client listener: >> 
End of headers
 << RTSP/1.0 200 OK
 << Public: OPTIONS, DESCRIBE, TEARDOWN, SETUP, PLAY, STOP
 << CSeq: 1
 << Session: 2
Client listener: >> ANNOUNCE rtsp://127.0.0.1:8666/live02 RTSP/1.0
Got method ANNOUNCE
Client listener: >> Content-Type: application/sdp
Client listener: >> CSeq: 2
Client listener: >> User-Agent: Lavf56.40.101
Client listener: >> Session: 2
Client listener: >> Content-Length: 341
Client listener: >> 
End of headers
Finished reading body, length=341
 << RTSP/1.0 405 Method Not Allowed
 << CSeq: 2
 << Session: 2
Returning error 405: Method Not Allowed
Got EOF on listener

Any idea ?

Thanks

**Comment by revmischa** [comment]
I asked in #ffmpeg and got no response...
Any way to maybe run ffmpeg with verbose logging?

**Comment by sladecraven** [comment]
Works, mismatch between ports, thanks !
