### ISSUE TITLE
How to rewrite rtsp-server with Python or Java

### ISSUE THREAD

**Issue by kerneldeveloper** [revmischa/rtsp-server#7]
Hi,
Thanks for your project. It's very useful.
Because I haven't learnt perl, I want to write a rtsp-server using python or java. I have searched many material, but I can't find systematic documents to help me understanding the principle of rtsp streaming server.So, could you give me some advice?
Thanks!

**Comment by revmischa** [comment]
Sure! Everyone you need to know about RTSP is here: https://www.ietf.org/rfc/rfc2326.txt
Specifically you should care about the ANNOUNCE, RECORD and DESCRIBE methods. 
Implementing the RTSP bit is fairly simple, you need to keep track of available streams and their descriptions. Most of the hard work in streaming media is handled by the SDP description and the actual RTP media stream. You need to receive the RTP packets from the sources and then relay them to the clients. You need to keep track of sessions and cseqs per client.
Other than that, try reading the code. Doesn't matter much if you know perl or not. If you have specific questions let me know.

**Comment by kerneldeveloper** [comment]
Thanks for your help!  I'll try it.
