### ISSUE TITLE
Latency induced by proxy ?

### ISSUE THREAD

**Issue by sladecraven** [revmischa/rtsp-server#8]
I would like to now if the rtsp-server add any latency on delivering RTP packets ? Or is there a buffer, keeping a certain amount of RTP packets before sending them ?
If this kind of buffering exists, i would like to control it / reduce it at its minimum.

Thanks for your support !

**Comment by revmischa** [comment]
It rebroadcasts the RTP packets as they come in without buffering https://github.com/revmischa/rtsp-server/blob/master/lib/RTSP/Server/RTPListener.pm#L95
